config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'homes#index'

  resources :homes, only: :index do
    match '/create_order' => 'homes#create_order', via: [:get, :post]
  end
  resources :users
  namespace :admins do

    namespace :products do
      post 'csv_upload'
    end

    resources :products do
      member do
        delete 'delete_image_attachment'
      end
    end
    
    resources :products
    resources :categories

  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
    has_many :products, through: :product_categories
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
    
    before_action :authenticate_admin!, except: [:index, :show]
    def index
        @search = params[:search]
        @categories = Category.all
        @categories = @categories.where("title LIKE? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
        @categories = @categories.page(params[:page]).per(30)
    end

    def show
        @category = Category.find(params[:id])
      end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.create(category_params)
        if @category.invalid?
            flash[:error] = @category.errors.full_messages
        end
        redirect_to action: :index
    end

    def edit
        @category = Category.find(params[:id])
    end
      
    def update
        @category = Category.find(params[:id])
        @category.update(category_params)
        redirect_to action: :index
    end
    
    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to action: :index
    end

    private
    def category_params
        params.require(:category).permit(:name, :description)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    before_action :authenticate_admin!, except: [:index, :show]
    def index
        @search = params[:search]
        @categories = Category.all
        @categories = @categories.where("title LIKE? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
        @categories = @categories.page(params[:page]).per(30)
    end

    def show
        @category = Category.find(params[:id])
      end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.create(category_params)
        if @category.invalid?
            flash[:error] = @category.errors.full_messages
        end
        redirect_to action: :index
    end

    def edit
        @category = Category.find(params[:id])
    end
      
    def update
        @category = Category.find(params[:id])
        @category.update(category_params)
        redirect_to action: :index
    end
    
    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to action: :index
    end

    private
    def category_params
        params.require(:category).permit(:name, :description)
    end
end

app/views/admins/categories/_form.slim
= form_with model: [:admins, category] do |f|
    div = f.text_field :name, placeholder: 'Category'
    div = f.text_area :description, placeholder: 'Write description here'
    div = f.submit 'Confirm'

app/views/admins/categories/edit.slim
h1 Edit category

div = link_to 'Back', admins_categories_path
br
= render 'form', category: @category

app/views/admins/categories/index.slim
.row.mt-2
    .col
        h1 Category list
.row.mt-2
    .col-6
        span =  link_to admins_products_path
            = button_tag 'Products', class: 'btn btn-primary'
    .col-6
        .float-right
            - if current_admin
                span = current_admin.email
                span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
                span.ml-3 = link_to 'Logout', destroy_admin_session_path, method: :delete
            - else 
                span.ml-3 = link_to 'Login', new_admin_session_path

.row.mt-2
  .col
    = form_tag admins_categories_path, method: :get do
    = text_field_tag 'search', @search, class: 'form-control', placeholder: 'Type something'
.row.mt-2
    .col
      table.table.table-border.table-striped.table-hover
        thead.thead-dark
          tr
            th ID
            th Category
            th Description
            th Created at
            th Updated at
            th Action
        tbody
          - @categories.each do |a|
            tr
              td = a.id
              td = a.name
              td = a.description
              td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
              td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
              td
                span
                  = link_to admins_category_path(a) do
                    i.fas.fa-eye
                - if current_admin 
                  span.ml-3
                    = link_to edit_admins_category_path(a) do
                      i.fas.fa-pen
                  span.ml-3
                    = link_to admins_category_path(a), method: :delete, data:{ confirm: "Are you sure?" } do
                      i.fas.fa-trash

.row
  - if current_admin 
    .col-6
      = paginate @categories
    .col-6
      .float-right
        div = link_to new_admins_category_path
            = button_tag 'Add new category', class: 'btn btn-primary'

app/views/admins/categories/new.slim
h1 Add new Category 

div = link_to 'Back', admins_categories_path
br
= render 'form', category: @category

app/views/admins/categories/show.slim
.row-mt2 
    h1 = @category.name

.row-mt2
    .col
      table.table.table-border
        thead.thead-dark
          tr
            th ID
            th Category
            th Description
            th Create at
            th Update at
        tbody
            tr
              td = @category.id
              td = @category.name
              td = @category.description
              td.font-weight-light = "#{time_ago_in_words(@category.created_at)} Ago"
              td.font-weight-light = "#{time_ago_in_words(@category.updated_at)} Ago"
.row-mt2
    .col-12
      .float-right
        div = link_to admins_categories_path
          = button_tag 'Back', class: 'btn btn-primary'