config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'homes#index'

  resources :homes, only: :index do
    match '/create_order' => 'homes#create_order', via: [:get, :post]
  end
  resources :users
  namespace :admins do

    namespace :products do
      post 'csv_upload'
    end

    resources :products do
      member do
        delete 'delete_image_attachment'
      end
    end
    
    resources :products
    resources :categories

  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_categories
    has_many :categories, through: :product_categories
    has_many :user, dependent: :destroy

    enum status: { draft: 0, published: 1, archived: 2 }

    has_one_attached :preview_image
    has_many_attached :images
    
    validates :stock, :numericality => { :greater_than_or_equal_to => 0 }
    validates :price, :numericality => { :greater_than => 0 }
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show]
  def index
    @search = params[:search]
    @products = Product.all
    @products = @products.where("title LIKE? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
    @products = @products.page(params[:page]).per(7)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    puts "This is how you print out sth."
    @product = Product.new
  end
  
  def create
    @product = Product.create(product_params)
    if @product.invalid?
      flash[:error] = @product.errors.full_messages
    end
    redirect_to action: :index
  end

  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to action: :index
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Product.create title: attr[0], description: attr[1], price: attr[2], stock: attr[3]
    end
    redirect_to action: :index
  end

  def delete_image_attachment
    @images = ActiveStorage::Attachment.find(params[:id])
    @images.purge
    redirect_to action: :edit
  end

  private

  def generate_csv(products)
    products.map {|a| [a.title, a.description, a.price, a.stock, a.updated_at.to_date].join(',') }.join("\n")
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :stock, :status, :preview_image, category_ids: [], images: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show]
  def index
    @search = params[:search]
    @products = Product.all
    @products = @products.where("title LIKE? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
    @products = @products.page(params[:page]).per(7)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    puts "This is how you print out sth."
    @product = Product.new
  end
  
  def create
    @product = Product.create(product_params)
    if @product.invalid?
      flash[:error] = @product.errors.full_messages
    end
    redirect_to action: :index
  end

  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to action: :index
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Product.create title: attr[0], description: attr[1], price: attr[2], stock: attr[3]
    end
    redirect_to action: :index
  end

  private

  def generate_csv(products)
    products.map {|a| [a.title, a.description, a.price, a.stock, a.updated_at.to_date].join(',') }.join("\n")
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :stock, :status, :preview_image, :images, category_ids: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_form.slim
= form_with model: [:admins, product] do |f|
  div Product:
  div = f.text_field :title, placeholder: 'Title'
  div = f.text_area :description, placeholder: 'Write description here'
  div = f.number_field :price, placeholder: 'Price'
  div = f.number_field :stock, placeholder: 'In the stock'
  div Preview Images:
  div 
    - if @product.preview_image.attached?
        = image_tag @product.preview_image, width: '90px'
    - else
        = f.file_field :preview_image
  div 
    - if @product.preview_image.attached?
      = link_to 'Delete Preview', delete_image_attachment_admins_product_path(@product.preview_image.id), method: :delete,
        data: { confirm: 'Are you sure to delete the preview' }, class: 'btn btn-danger'
  div Image: 
  div = f.file_field :images, multiple: true
  div Catagory
  div = f.collection_check_boxes :category_ids, Category.all, :id, :name
  div
    - if @product.images.attached?
      - @product.images.each do |image|
        div 
          span
            = image_tag image, width: '80px'
          span.ml-2
            = link_to 'Delete Image', delete_image_attachment_admins_product_path(image.id), method: :delete,
              data: { confirm: 'Are you sure to delete the preview' }, class: 'btn btn-danger'
  div Status
  div = f.select :status, Product.statuses.keys
  div = f.submit 'Confirm'

app/views/admins/products/edit.slim
h1 Edit product

div = link_to 'Back', admins_products_path
br
= render 'form', product: @product

app/views/admins/products/index.slim
.row.mt-2
  .col-9
    h2 Product list
  .col-3 
    - if current_admin
      .float-right
        span = current_admin.email
.row.mt-2
  .col-4
    = form_tag admins_products_path, method: :get do
    = text_field_tag 'search', @search, class: 'form-control', placeholder: 'Type something'

  .col-2
    .float-right
      - if current_admin
          span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
          span.ml-3 = link_to destroy_admin_session_path, method: :delete
                    = button_tag 'Logout', class: 'btn btn-secondary float-right'
      - else 
          span.ml-3 = link_to new_admin_session_path
                    = button_tag 'Login', class: 'btn btn-secondary float-right'

  .col-2 
    .float-right
      span.ml-3 = link_to admins_products_path(format: :csv) do 
        = button_tag 'Download CSV', class: 'btn btn-secondary float-right'

  .col-2
    -if current_admin
      .float-right
        span.ml-3 = link_to users_path
          = button_tag 'Orders', class: 'btn btn-primary'

  .col-2
    .float-right
      span.ml-3 = link_to admins_categories_path
        = button_tag 'Categories', class: 'btn btn-primary'

.row.mt-2
    .col
      table.table.table-border.table-striped.table-hover
        thead.thead-dark
          tr
            th Preview
            th Title
            th Description
            th Price
            th Stock
            th Images
            th Categories
            th Status
            th Updated at
            th Action
        tbody
          - @products.each do |a|
            tr
              td
                - if a.preview_image.attached?
                  = image_tag a.preview_image, width: '64px'
              td = a.title
              td = a.description
              td = a.price
              td = a.stock
              td 
                - a.images.each do |image|
                  = image_tag image, width: '32px'
              td = a.categories&.map(&:name)&.join(', ').presence || 'N/A'
              td = a.status
              td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
              td
                span
                  = link_to admins_product_path(a) do
                    i.fas.fa-eye
                - if current_admin 
                  span.ml-3
                    = link_to edit_admins_product_path(a) do
                      i.fas.fa-pen
                  span.ml-3
                    = link_to admins_product_path(a), method: :delete, data:{ confirm: "Are you sure?" } do
                      i.fas.fa-trash

hr
.row.mt-2
  .col-6
    = paginate @products
  - if current_admin 
    .col-2
      .float-right
        = form_tag admins_products_csv_upload_path, multipart: true do
          div = file_field_tag :csv_file
          div = submit_tag :upload
    .col-2
      .float-right
        div = link_to new_admins_product_path
          = button_tag 'Add new product', class: 'btn btn-primary'
hr
  

app/views/admins/products/new.slim
h1 Add new product

div = link_to 'Back', admins_products_path
br
= render 'form', product: @product

app/views/admins/products/show.slim
.row-mt2 
    h2 Product details:

hr

.row
  .col-6
    .card
      .card-img-top
        - if @product.preview_image.attached?
          = image_tag @product.preview_image, width: '100%'
      //.col-md-8 
      .card-body
          .card-title 
            h3 = @product.title
          .row 
            .col 
              = @product.price
          .row 
            .col 
              = @product.stock
          .row 
            .col 
              = @product.categories&.map(&:name)&.join(', ').presence || 'N/A'
          .row 
            .col 
              = @product.status
          .row 
            .col
               = "#{time_ago_in_words(@product.updated_at)} Ago"
  .col-6
    .card
      .card-body
          .row 
            .col 
              = @product.description
    .card
      .card-body
          .row 
            .col 
              - @product.images.each do |image|
                = image_tag image, width: '128px'

/ .row-mt2
      table.table.table-border
        thead.thead-dark
          tr
            th Preview
            th Title
            th Description
            th Images
            th Price
            th In Stock
        tbody
            tr
              td
                - if @product.preview_image.attached?
                  = image_tag @product.preview_image, width: '64px'
              td = @product.title
              td = @product.description
              td
                - @product.images.each do |image|
                  = image_tag image, width: '60px'
              td = @product.price
              td = @product.stock

.row-mt2
    .col-12
      .float-right
        - if current_admin 
          .row
            span.ml-6
               = link_to edit_admins_product_path(@product)
                = button_tag 'Edit', class: 'btn btn-primary'
            span.ml-6 = link_to admins_products_path
                = button_tag 'Back', class: 'btn btn-primary'
        - else 
          div = link_to homes_path
            = button_tag 'Back', class: 'btn btn-primary'